variable "identifier" {}
variable "environment" {}
variable "owner" {}
variable "project" {}
variable "aws_vpc_id" {}
variable "engine" {}
variable "engine_version" {}
variable "app_security_group_id" {}
variable "private_subnet_ids" {}
variable "master_password" {}
variable "master_username" {}
variable "skip_final_snapshot" {}
variable "instance_class" {}
variable "apply_immediately" {}
