variable owner {}
variable project {}
variable environment {}
variable repository_branch {}
variable code_provider {}
variable repository_url {}
variable maestro_image {}
variable aws_iam_role {}
variable aws_security_group_lb {}
variable aws_security_group_app {}
variable aws_security_group_cb {}
variable aws_subnets {}
variable aws_vpc_id {}