variable owner {}
variable project {}
variable environment {}
variable repository_branch {}
variable code_provider {}
variable repository_url {}
variable maestro_image {}
variable aws_iam_role {}
variable aws_public_subnets {}
variable aws_private_subnets {}
variable aws_vpc_id {}